// ============================================================
//  PARKOPIA – Configuration & Constants
// ============================================================

const CONFIG = {
    // Grid
    GRID_WIDTH: 60,
    GRID_HEIGHT: 60,
    TILE_W: 64,
    TILE_H: 32,

    // Camera
    CAMERA_SPEED: 8,
    ZOOM_MIN: 0.4,
    ZOOM_MAX: 2.0,
    ZOOM_STEP: 0.1,

    // Economy
    STARTING_MONEY: 10000,
    ENTRANCE_FEE: 10,
    UPKEEP_INTERVAL: 600, // ticks between upkeep charges

    // Guests
    MAX_GUESTS: 120,
    GUEST_SPAWN_RATE: 180, // ticks between spawns (at rating 1)
    GUEST_SPEED: 0.6,
    GUEST_PATIENCE: 800,

    // Time
    TICKS_PER_DAY: 3600,

    // Colors (terrain)
    COLOR_GRASS: '#7ec850',
    COLOR_GRASS_ALT: '#72b847',
    COLOR_DIRT: '#c4a265',
    COLOR_WATER: '#4fa8d4',
    COLOR_WATER_DEEP: '#3d8ab8',
    COLOR_PATH: '#d4c6a1',
    COLOR_PATH_EDGE: '#b8a882',
};

// Building definitions
const BUILDINGS = {
    // === PATHS ===
    path: {
        name: 'Path',
        category: 'paths',
        cost: 10,
        size: [1, 1],
        walkable: true,
        description: 'Guests walk on paths to reach rides.',
        upkeep: 0,
    },
    wide_path: {
        name: 'Wide Path',
        category: 'paths',
        cost: 25,
        size: [1, 1],
        walkable: true,
        description: 'A wider walkway for heavy traffic.',
        upkeep: 0,
        variant: 'wide',
    },

    // === RIDES ===
    carousel: {
        name: 'Carousel',
        category: 'rides',
        cost: 500,
        size: [2, 2],
        ticketPrice: 5,
        capacity: 8,
        rideDuration: 200,
        excitement: 2,
        description: 'A gentle spinning ride loved by all ages.',
        upkeep: 5,
    },
    ferris_wheel: {
        name: 'Ferris Wheel',
        category: 'rides',
        cost: 1200,
        size: [3, 3],
        ticketPrice: 8,
        capacity: 12,
        rideDuration: 350,
        excitement: 4,
        description: 'A towering wheel with panoramic views.',
        upkeep: 12,
    },
    roller_coaster: {
        name: 'Roller Coaster',
        category: 'rides',
        cost: 2500,
        size: [4, 3],
        ticketPrice: 12,
        capacity: 16,
        rideDuration: 250,
        excitement: 8,
        description: 'A thrilling high-speed coaster!',
        upkeep: 25,
    },
    bumper_cars: {
        name: 'Bumper Cars',
        category: 'rides',
        cost: 800,
        size: [2, 2],
        ticketPrice: 6,
        capacity: 10,
        rideDuration: 200,
        excitement: 3,
        description: 'Crash into friends in colourful cars.',
        upkeep: 8,
    },
    tea_cups: {
        name: 'Tea Cups',
        category: 'rides',
        cost: 600,
        size: [2, 2],
        ticketPrice: 4,
        capacity: 8,
        rideDuration: 180,
        excitement: 2,
        description: 'Spin inside giant teacups!',
        upkeep: 6,
    },
    log_flume: {
        name: 'Log Flume',
        category: 'rides',
        cost: 1800,
        size: [3, 2],
        ticketPrice: 10,
        capacity: 8,
        rideDuration: 300,
        excitement: 6,
        description: 'A watery ride with a big splash finish.',
        upkeep: 18,
    },
    drop_tower: {
        name: 'Drop Tower',
        category: 'rides',
        cost: 1500,
        size: [2, 2],
        ticketPrice: 10,
        capacity: 8,
        rideDuration: 150,
        excitement: 7,
        description: 'Stomach-dropping freefall from the sky.',
        upkeep: 15,
    },

    // === FOOD ===
    burger_stand: {
        name: 'Burger Stand',
        category: 'food',
        cost: 300,
        size: [1, 1],
        foodPrice: 6,
        hungerRelief: 60,
        description: 'Juicy burgers for hungry guests.',
        upkeep: 4,
    },
    ice_cream_cart: {
        name: 'Ice Cream',
        category: 'food',
        cost: 200,
        size: [1, 1],
        foodPrice: 4,
        hungerRelief: 30,
        description: 'Cool treats on a hot day.',
        upkeep: 2,
    },
    drinks_booth: {
        name: 'Drinks',
        category: 'food',
        cost: 200,
        size: [1, 1],
        foodPrice: 3,
        thirstRelief: 80,
        description: 'Refreshing beverages for thirsty guests.',
        upkeep: 2,
    },
    cotton_candy: {
        name: 'Cotton Candy',
        category: 'food',
        cost: 150,
        size: [1, 1],
        foodPrice: 3,
        hungerRelief: 15,
        happinessBoost: 10,
        description: 'Fluffy sugar clouds of joy.',
        upkeep: 1,
    },
    pizza_stand: {
        name: 'Pizza',
        category: 'food',
        cost: 350,
        size: [1, 1],
        foodPrice: 7,
        hungerRelief: 70,
        description: 'Cheesy slices for the whole family.',
        upkeep: 4,
    },

    // === SCENERY ===
    tree: {
        name: 'Tree',
        category: 'scenery',
        cost: 30,
        size: [1, 1],
        beauty: 3,
        description: 'A lovely shade tree.',
        upkeep: 0,
    },
    flower_bed: {
        name: 'Flowers',
        category: 'scenery',
        cost: 20,
        size: [1, 1],
        beauty: 4,
        description: 'Colourful flower arrangements.',
        upkeep: 1,
    },
    fountain: {
        name: 'Fountain',
        category: 'scenery',
        cost: 250,
        size: [1, 1],
        beauty: 8,
        description: 'An elegant water feature.',
        upkeep: 3,
    },
    bench: {
        name: 'Bench',
        category: 'scenery',
        cost: 15,
        size: [1, 1],
        beauty: 1,
        restValue: 20,
        description: 'A place for tired guests to rest.',
        upkeep: 0,
    },
    lamp: {
        name: 'Lamp Post',
        category: 'scenery',
        cost: 40,
        size: [1, 1],
        beauty: 2,
        description: 'Illuminates the park at night.',
        upkeep: 1,
    },
    trash_can: {
        name: 'Trash Can',
        category: 'scenery',
        cost: 10,
        size: [1, 1],
        cleanRadius: 3,
        description: 'Keeps the park tidy.',
        upkeep: 0,
    },
    statue: {
        name: 'Statue',
        category: 'scenery',
        cost: 400,
        size: [1, 1],
        beauty: 10,
        description: 'A grand park centrepiece.',
        upkeep: 2,
    },
    hedge: {
        name: 'Hedge',
        category: 'scenery',
        cost: 15,
        size: [1, 1],
        beauty: 2,
        description: 'Neatly trimmed greenery.',
        upkeep: 0,
    },

    // === BUILDINGS ===
    entrance: {
        name: 'Park Entrance',
        category: 'buildings',
        cost: 0,
        size: [2, 1],
        description: 'The main gate — guests arrive here.',
        upkeep: 0,
        unique: true,
    },
    restroom: {
        name: 'Restroom',
        category: 'buildings',
        cost: 300,
        size: [1, 1],
        bathroomRelief: 100,
        description: 'Essential facilities for guest comfort.',
        upkeep: 5,
    },
    gift_shop: {
        name: 'Gift Shop',
        category: 'buildings',
        cost: 500,
        size: [1, 1],
        shopIncome: 8,
        happinessBoost: 5,
        description: 'Souvenirs and memorabilia.',
        upkeep: 6,
    },
    info_booth: {
        name: 'Info Booth',
        category: 'buildings',
        cost: 200,
        size: [1, 1],
        description: 'Helps guests navigate the park.',
        upkeep: 3,
    },
    first_aid: {
        name: 'First Aid',
        category: 'buildings',
        cost: 350,
        size: [1, 1],
        description: 'Medical assistance for guests.',
        upkeep: 5,
    },
};

// Categories for toolbar display order
const CATEGORY_ITEMS = {
    paths: ['path', 'wide_path'],
    rides: ['carousel', 'ferris_wheel', 'roller_coaster', 'bumper_cars', 'tea_cups', 'log_flume', 'drop_tower'],
    food: ['burger_stand', 'ice_cream_cart', 'drinks_booth', 'cotton_candy', 'pizza_stand'],
    scenery: ['tree', 'flower_bed', 'fountain', 'bench', 'lamp', 'trash_can', 'statue', 'hedge'],
    buildings: ['restroom', 'gift_shop', 'info_booth', 'first_aid'],
};
