// ============================================================
//  PARKOPIA – Configuration & Constants
// ============================================================

const CONFIG = {
    // Grid
    GRID_WIDTH: 60,
    GRID_HEIGHT: 60,
    TILE_W: 64,
    TILE_H: 32,

    // Camera
    CAMERA_SPEED: 8,
    ZOOM_MIN: 0.4,
    ZOOM_MAX: 2.0,
    ZOOM_STEP: 0.1,

    // Economy
    STARTING_MONEY: 10000,
    ENTRANCE_FEE: 10,
    UPKEEP_INTERVAL: 600, // ticks between upkeep charges

    // Guests
    MAX_GUESTS: 120,
    GUEST_SPAWN_RATE: 180, // ticks between spawns (at rating 1)
    GUEST_SPEED: 0.6,
    GUEST_PATIENCE: 800,

    // Time
    TICKS_PER_DAY: 3600,

    // Colors (terrain)
    COLOR_GRASS: '#7ec850',
    COLOR_GRASS_ALT: '#72b847',
    COLOR_DIRT: '#c4a265',
    COLOR_WATER: '#4fa8d4',
    COLOR_WATER_DEEP: '#3d8ab8',
    COLOR_PATH: '#d4c6a1',
    COLOR_PATH_EDGE: '#b8a882',
};

// Building definitions
const BUILDINGS = {
    // === PATHS ===
    path: {
        name: 'Path',
        category: 'paths',
        cost: 10,
        size: [1, 1],
        walkable: true,
        description: 'Guests walk on paths to reach rides.',
        upkeep: 0,
    },
    wide_path: {
        name: 'Wide Path',
        category: 'paths',
        cost: 25,
        size: [1, 1],
        walkable: true,
        description: 'A wider walkway for heavy traffic.',
        upkeep: 0,
        variant: 'wide',
    },

    // === RIDES ===
    carousel: {
        name: 'Carousel',
        category: 'rides',
        cost: 500,
        size: [2, 2],
        ticketPrice: 5,
        capacity: 8,
        rideDuration: 200,
        excitement: 2,
        description: 'A gentle spinning ride loved by all ages.',
        upkeep: 5,
    },
    ferris_wheel: {
        name: 'Ferris Wheel',
        category: 'rides',
        cost: 1200,
        size: [3, 3],
        ticketPrice: 8,
        capacity: 12,
        rideDuration: 350,
        excitement: 4,
        description: 'A towering wheel with panoramic views.',
        upkeep: 12,
    },
    roller_coaster: {
        name: 'Roller Coaster',
        category: 'rides',
        cost: 2500,
        size: [4, 3],
        ticketPrice: 12,
        capacity: 16,
        rideDuration: 250,
        excitement: 8,
        description: 'A thrilling high-speed coaster!',
        upkeep: 25,
    },
    bumper_cars: {
        name: 'Bumper Cars',
        category: 'rides',
        cost: 800,
        size: [2, 2],
        ticketPrice: 6,
        capacity: 10,
        rideDuration: 200,
        excitement: 3,
        description: 'Crash into friends in colourful cars.',
        upkeep: 8,
    },
    tea_cups: {
        name: 'Tea Cups',
        category: 'rides',
        cost: 600,
        size: [2, 2],
        ticketPrice: 4,
        capacity: 8,
        rideDuration: 180,
        excitement: 2,
        description: 'Spin inside giant teacups!',
        upkeep: 6,
    },
    log_flume: {
        name: 'Log Flume',
        category: 'rides',
        cost: 1800,
        size: [3, 2],
        ticketPrice: 10,
        capacity: 8,
        rideDuration: 300,
        excitement: 6,
        description: 'A watery ride with a big splash finish.',
        upkeep: 18,
    },
    drop_tower: {
        name: 'Drop Tower',
        category: 'rides',
        cost: 1500,
        size: [2, 2],
        ticketPrice: 10,
        capacity: 8,
        rideDuration: 150,
        excitement: 7,
        description: 'Stomach-dropping freefall from the sky.',
        upkeep: 15,
    },
    swing_ride: {
        name: 'Swing Ride',
        category: 'rides',
        cost: 700,
        size: [2, 2],
        ticketPrice: 5,
        capacity: 10,
        rideDuration: 180,
        excitement: 3,
        description: 'Soar through the air on spinning swings.',
        upkeep: 7,
    },
    pirate_ship: {
        name: 'Pirate Ship',
        category: 'rides',
        cost: 1000,
        size: [3, 2],
        ticketPrice: 8,
        capacity: 12,
        rideDuration: 220,
        excitement: 5,
        description: 'A swinging galleon for brave buccaneers!',
        upkeep: 10,
    },
    go_karts: {
        name: 'Go Karts',
        category: 'rides',
        cost: 1100,
        size: [3, 2],
        ticketPrice: 9,
        capacity: 8,
        rideDuration: 250,
        excitement: 5,
        description: 'Race around the track at top speed!',
        upkeep: 12,
    },
    haunted_house: {
        name: 'Haunted House',
        category: 'rides',
        cost: 1600,
        size: [3, 3],
        ticketPrice: 10,
        capacity: 10,
        rideDuration: 280,
        excitement: 6,
        description: 'A spooky dark ride full of surprises.',
        upkeep: 14,
    },
    water_slide: {
        name: 'Water Slide',
        category: 'rides',
        cost: 2000,
        size: [3, 3],
        ticketPrice: 11,
        capacity: 6,
        rideDuration: 200,
        excitement: 7,
        description: 'A towering slide with a splashy finish!',
        upkeep: 20,
    },

    // === CUSTOM COASTER ===
    coaster_station: {
        name: 'Coaster Station',
        category: 'rides',
        cost: 1500,
        size: [2, 2],
        ticketPrice: 10,
        capacity: 12,
        rideDuration: 200,
        excitement: 3,
        description: 'Build your own coaster! Place tracks to increase excitement.',
        upkeep: 15,
        isCoasterStation: true,
    },
    track_straight: {
        name: 'Track: Straight',
        category: 'coaster',
        cost: 50,
        size: [1, 1],
        description: 'Straight coaster track section.',
        upkeep: 0,
        isTrack: true,
        excitementBonus: 1,
    },
    track_curve: {
        name: 'Track: Curve',
        category: 'coaster',
        cost: 75,
        size: [1, 1],
        description: 'Curved coaster track for turns.',
        upkeep: 0,
        isTrack: true,
        excitementBonus: 2,
    },
    track_slope: {
        name: 'Track: Slope',
        category: 'coaster',
        cost: 100,
        size: [1, 1],
        description: 'Elevated track — adds a thrilling hill!',
        upkeep: 0,
        isTrack: true,
        excitementBonus: 3,
    },

    // === FOOD ===
    burger_stand: {
        name: 'Burger Stand',
        category: 'food',
        cost: 300,
        size: [1, 1],
        foodPrice: 6,
        hungerRelief: 60,
        description: 'Juicy burgers for hungry guests.',
        upkeep: 4,
    },
    ice_cream_cart: {
        name: 'Ice Cream',
        category: 'food',
        cost: 200,
        size: [1, 1],
        foodPrice: 4,
        hungerRelief: 30,
        description: 'Cool treats on a hot day.',
        upkeep: 2,
    },
    drinks_booth: {
        name: 'Drinks',
        category: 'food',
        cost: 200,
        size: [1, 1],
        foodPrice: 3,
        thirstRelief: 80,
        description: 'Refreshing beverages for thirsty guests.',
        upkeep: 2,
    },
    cotton_candy: {
        name: 'Cotton Candy',
        category: 'food',
        cost: 150,
        size: [1, 1],
        foodPrice: 3,
        hungerRelief: 15,
        happinessBoost: 10,
        description: 'Fluffy sugar clouds of joy.',
        upkeep: 1,
    },
    pizza_stand: {
        name: 'Pizza',
        category: 'food',
        cost: 350,
        size: [1, 1],
        foodPrice: 7,
        hungerRelief: 70,
        description: 'Cheesy slices for the whole family.',
        upkeep: 4,
    },
    popcorn_cart: {
        name: 'Popcorn',
        category: 'food',
        cost: 120,
        size: [1, 1],
        foodPrice: 2,
        hungerRelief: 15,
        happinessBoost: 5,
        description: 'Buttery popcorn — a park classic!',
        upkeep: 1,
    },
    taco_stand: {
        name: 'Taco Stand',
        category: 'food',
        cost: 320,
        size: [1, 1],
        foodPrice: 7,
        hungerRelief: 65,
        description: 'Crunchy tacos with all the fixings.',
        upkeep: 4,
    },
    sushi_bar: {
        name: 'Sushi Bar',
        category: 'food',
        cost: 500,
        size: [1, 1],
        foodPrice: 12,
        hungerRelief: 75,
        happinessBoost: 8,
        description: 'Premium sushi for discerning guests.',
        upkeep: 6,
    },
    juice_bar: {
        name: 'Juice Bar',
        category: 'food',
        cost: 280,
        size: [1, 1],
        foodPrice: 5,
        thirstRelief: 90,
        happinessBoost: 5,
        description: 'Fresh smoothies and juices.',
        upkeep: 3,
    },

    // === SCENERY ===
    tree: {
        name: 'Tree',
        category: 'scenery',
        cost: 30,
        size: [1, 1],
        beauty: 3,
        description: 'A lovely shade tree.',
        upkeep: 0,
    },
    flower_bed: {
        name: 'Flowers',
        category: 'scenery',
        cost: 20,
        size: [1, 1],
        beauty: 4,
        description: 'Colourful flower arrangements.',
        upkeep: 1,
    },
    fountain: {
        name: 'Fountain',
        category: 'scenery',
        cost: 250,
        size: [1, 1],
        beauty: 8,
        description: 'An elegant water feature.',
        upkeep: 3,
    },
    bench: {
        name: 'Bench',
        category: 'scenery',
        cost: 15,
        size: [1, 1],
        beauty: 1,
        restValue: 20,
        description: 'A place for tired guests to rest.',
        upkeep: 0,
    },
    lamp: {
        name: 'Lamp Post',
        category: 'scenery',
        cost: 40,
        size: [1, 1],
        beauty: 2,
        description: 'Illuminates the park at night.',
        upkeep: 1,
    },
    trash_can: {
        name: 'Trash Can',
        category: 'scenery',
        cost: 10,
        size: [1, 1],
        cleanRadius: 3,
        description: 'Keeps the park tidy.',
        upkeep: 0,
    },
    statue: {
        name: 'Statue',
        category: 'scenery',
        cost: 400,
        size: [1, 1],
        beauty: 10,
        description: 'A grand park centrepiece.',
        upkeep: 2,
    },
    hedge: {
        name: 'Hedge',
        category: 'scenery',
        cost: 15,
        size: [1, 1],
        beauty: 2,
        description: 'Neatly trimmed greenery.',
        upkeep: 0,
    },
    pond: {
        name: 'Pond',
        category: 'scenery',
        cost: 180,
        size: [1, 1],
        beauty: 6,
        description: 'A tranquil decorative pond.',
        upkeep: 1,
    },
    topiary: {
        name: 'Topiary',
        category: 'scenery',
        cost: 120,
        size: [1, 1],
        beauty: 5,
        description: 'An ornamental shaped shrub.',
        upkeep: 2,
    },
    rose_garden: {
        name: 'Rose Garden',
        category: 'scenery',
        cost: 350,
        size: [1, 1],
        beauty: 12,
        description: 'A stunning display of roses.',
        upkeep: 3,
    },
    clock_tower: {
        name: 'Clock Tower',
        category: 'scenery',
        cost: 1200,
        size: [2, 2],
        beauty: 18,
        description: 'A grand landmark visible across the park.',
        upkeep: 5,
    },

    // === BUILDINGS ===
    entrance: {
        name: 'Park Entrance',
        category: 'buildings',
        cost: 0,
        size: [2, 1],
        description: 'The main gate — guests arrive here.',
        upkeep: 0,
        unique: true,
    },
    restroom: {
        name: 'Restroom',
        category: 'buildings',
        cost: 300,
        size: [1, 1],
        bathroomRelief: 100,
        description: 'Essential facilities for guest comfort.',
        upkeep: 5,
    },
    gift_shop: {
        name: 'Gift Shop',
        category: 'buildings',
        cost: 500,
        size: [1, 1],
        shopIncome: 8,
        happinessBoost: 5,
        description: 'Souvenirs and memorabilia.',
        upkeep: 6,
    },
    info_booth: {
        name: 'Info Booth',
        category: 'buildings',
        cost: 200,
        size: [1, 1],
        description: 'Helps guests navigate the park.',
        upkeep: 3,
    },
    first_aid: {
        name: 'First Aid',
        category: 'buildings',
        cost: 350,
        size: [1, 1],
        description: 'Medical assistance for guests.',
        upkeep: 5,
    },
    arcade: {
        name: 'Arcade',
        category: 'buildings',
        cost: 600,
        size: [1, 1],
        shopIncome: 10,
        happinessBoost: 8,
        description: 'Retro games and prizes for all!',
        upkeep: 6,
    },
    lounge: {
        name: 'Lounge',
        category: 'buildings',
        cost: 700,
        size: [1, 1],
        restValue: 50,
        happinessBoost: 5,
        description: 'A premium rest area with comfy seating.',
        upkeep: 5,
    },
};

// Categories for toolbar display order
const CATEGORY_ITEMS = {
    paths: ['path', 'wide_path'],
    rides: ['carousel', 'tea_cups', 'swing_ride', 'bumper_cars', 'pirate_ship', 'go_karts', 'ferris_wheel', 'log_flume', 'drop_tower', 'haunted_house', 'water_slide', 'roller_coaster', 'coaster_station'],
    food: ['popcorn_cart', 'burger_stand', 'ice_cream_cart', 'drinks_booth', 'cotton_candy', 'pizza_stand', 'taco_stand', 'juice_bar', 'sushi_bar'],
    scenery: ['tree', 'flower_bed', 'bench', 'trash_can', 'hedge', 'lamp', 'pond', 'topiary', 'fountain', 'statue', 'rose_garden', 'clock_tower'],
    buildings: ['restroom', 'info_booth', 'first_aid', 'gift_shop', 'arcade', 'lounge'],
    coaster: ['track_straight', 'track_curve', 'track_slope'],
};
